### PR TITLE
authentication - ssh timeout

### PR DESCRIPTION
**Pull request by danlavu**
tests are hitting the timeout to soon, prematurely failing the test

### CODE REVIEW

**Comment by danlavu** [comment]
tox was failing, so when I was fixing looking at the tox errors, I ended up standardizing the guide titles, please look at https://github.com/SSSD/sssd-test-framework/pull/116 first

**Comment by danlavu** [comment]
Tox is passing, the reason for error is [this bug in sphinx](https://github.com/sphinx-doc/sphinx/issues/12589)

```
  py3: OK (7.30=setup[2.16]+cmd[5.14] seconds)
  py3-upstream: OK (7.28=setup[2.11]+cmd[5.17] seconds)
  py311: OK (7.21=setup[2.05]+cmd[5.16] seconds)
  py311-upstream: OK (7.46=setup[2.31]+cmd[5.15] seconds)
  lint: OK (5.47=setup[2.28]+cmd[0.33,0.79,0.31,1.65,0.11] seconds)
  lint-upstream: OK (4.51=setup[2.04]+cmd[0.34,0.78,0.15,1.10,0.10] seconds)
  docs: OK (3.45=setup[2.30]+cmd[1.14] seconds)
  docs-upstream: OK (3.16=setup[2.09]+cmd[1.07] seconds)
  congratulations :) (45.89 seconds)
```

**Review by jakub-vavra-cz — APPROVED** [review]
LGTM

**Comment by alexey-tikhonov** [comment]
@sumit-bose asked for logs to understand the reason of the need to increase timeout.

**Comment by sumit-bose** [comment]
> @sumit-bose asked for logs to understand the reason of the need to increase timeout.

Hi @danlavu,

where can I find some debug logs which show the failure with the lower timeout?

bye,
Sumit

**Comment by danlavu** [comment]
@sumit-bose ack, will get some logs for you, thanks.

**Comment by danlavu** [comment]
@sumit-bose I looked for the existing run, but I'm not able to reproduce the issue. I've since ran the tests again locally and the user denials resolves within a second. I'm closing this PR.

**Pull request closed without merging**
