### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ikerexxe**
While implementing shadow's test framework I discovered several issues that I've fixed

### CODE REVIEW

**Review by danlavu — APPROVED** [review]
Conditional approval, there is a test that is failing.

**Review by pbrezina — APPROVED** [review]

**Comment by ikerexxe** [comment]
I'm not really sure what is happening here, but the CI errors are the ones fixed at https://github.com/SSSD/sssd-test-framework/pull/138 and I already rebased my branch on top of it :confused:

**Comment by pbrezina** [comment]
Hmm. Let's merge it and we'll see.

**Comment by pbrezina** [comment]
This fixes it https://github.com/SSSD/sssd-test-framework/pull/143

**Comment by ikerexxe** [comment]
> This fixes it #143

What? :open_mouth: in that case I am having a hard time understanding how the CI was green for https://github.com/SSSD/sssd-test-framework/pull/138.

**Comment by pbrezina** [comment]
I have know idea, I was mainly looking at CI result as well in this case. You can try to checkout the code and build it locally.

**Pull request merged**
