### PR TITLE
utils: passwd from shadow utils

### PR DESCRIPTION
**Pull request by thalman**
The passwd binary from shadow utils has slightly different outputs.

### CODE REVIEW

**Comment by thalman** [comment]
I struggle with running the latest version of the tests framework, so I did not run it yet with this update.

But since it is simple change tested outside framework with command line `expect`, it should work.

**Review by alexey-tikhonov — APPROVED** [review]

**Review by ikerexxe — APPROVED** [review]
LGTM! I checked locally that this worked correctly with the new `passwd` and I opened https://github.com/SSSD/sssd/pull/7192 to check the changes didn't break the existing `passwd` tests. Thank you!

**Comment by ikerexxe** [comment]
@thalman can you rebase on top of master? Then, we'll be able to merge the PR.

**Comment by thalman** [comment]
> @thalman can you rebase on top of master? Then, we'll be able to merge the PR.

@ikerexxe rebased

**Comment by ikerexxe** [comment]
CI failures are unrelated so merging.

**Pull request merged**
