### PR TITLE
ipa: add support for external group members

### PR DESCRIPTION
**Pull request by pbrezina**

### CODE REVIEW

**Comment by ikerexxe** [comment]
Question for testing purposes. `ipa.group("thegrup").add_member("--external sometext")` can be used to test this logic, right?

**Comment by pbrezina** [comment]
`.add_member("user@domain")`, e.g. `.add_member("Administrator@samba.test")`

**Review by ikerexxe — APPROVED** [review]
I knew I was doing something wrong, thanks for the examples. LGTM!

**Comment by pbrezina** [comment]
I had it this way originally, then switched. I'm fine both ways. I guess this depends on how familiar are you with IPA, it uses the same command as IPA users and group and you can add all in single command. I.e. `ipa group-add-member group --users ... --groups ... --external ...`. That's why I merged it in the end and just put it into method description. If we go with two methods, then you need to add two calls to do the same thing.

It's your call.

**Comment by justin-stephenson** [comment]
> I had it this way originally, then switched. I'm fine both ways. I guess this depends on how familiar are you with IPA, it uses the same command as IPA users and group and you can add all in single command. I.e. `ipa group-add-member group --users ... --groups ... --external ...`. That's why I merged it in the end and just put it into method description. If we go with two methods, then you need to add two calls to do the same thing.
> 
> It's your call.

Okay let's keep it as is. Thanks for the explanation.

**Review by justin-stephenson — APPROVED** [review]
Ack, thank you.

**Pull request merged**
