### PR TITLE
local: Use -f to execute groupdel

### PR DESCRIPTION
**Pull request by justin-stephenson**

### CODE REVIEW

**Comment by pbrezina** [comment]
Why? `--force` is valid option. If there is some problem, please, add description to the commit message.

**Comment by alexey-tikhonov** [comment]
> Why? `--force` is valid option. If there is some problem, please, add description to the commit message.

'shadow-utils' tool doesn't support '--force' on centos-8 package.

**Comment by alexey-tikhonov** [comment]
It's an addition to incomplete 66528081e63193d1e66840e8816c26d4d40f4e08

**Comment by justin-stephenson** [comment]
> Why? `--force` is valid option. If there is some problem, please, add description to the commit message.

Updated.

**Pull request merged**
