### PR TITLE
Tools: journalctl added

### PR DESCRIPTION
**Pull request by patriki01**
I added command for ``journalctl``.  I included only what I thought are most commonly used parameters. Feel free to suggest change.

### CODE REVIEW

**Comment by danlavu** [comment]
It'd be nice to add a doc entry for this and provide the following examples, 

1. Typical usage, getting output from journalctl
2. Assertion usage, how to use it and search for a string in the journal for a test case 

assert client.utils.tools.journalctl(grep="search string").rc == 0
assert client.utils.tools.journal(grep="bad string").rc not 0

**Comment by patriki01** [comment]
I added example usage as you proposed.

**Review by ikerexxe — APPROVED** [review]
I'd also add the `--system` and `--user` options, I think I'm using them quite often.

However, this is only an optional improvement so I'm approving this PR.

**Comment by patriki01** [comment]
I added those options @ikerexxe

**Comment by ikerexxe** [comment]
@danlavu, @pbrezina do you mind reviewing this PR?

**Comment by danlavu** [comment]
@pbrezina  ack

@patriki01 I suppose we can take the comment about the assertions out then.

**Comment by patriki01** [comment]
Okay, I move it there: https://github.com/next-actions/pytest-mh/pull/23

**Pull request closed without merging**
