### PR TITLE
[DRAFT] Create utility to manage Samba Standalone Server.

### PR DESCRIPTION
**Pull request by dkarpele**
- New class `SambaUtils` inherits from `SSSDUtils`.
- Methods `share` and `smbclient` has been added to `SambaUtils` because they are specific for samba.
- Documentation has been updated.

### CODE REVIEW

**Comment by dkarpele** [comment]
Test for this utility is in internal gitlab in identity-management/samba-tests, MR#543

**Comment by pbrezina** [comment]
@sidecontrol Do we have any tests for SSSD that utilize smbclient or should Denis move this to samba repository?

**Comment by sidecontrol** [comment]
> @sidecontrol Do we have any tests for SSSD that utilize smbclient or should Denis move this to samba repository?

The smbclient command,  no. 

The closest tests that we have that use samba, are mounting cifs shares and checking authentication and authorization to the shares.

**Comment by dkarpele** [comment]
Closing because the functionality will be implemented in the external repo.

**Pull request closed without merging**
