### PR TITLE
ssh: adding expect reponse to connection closed

### PR DESCRIPTION
**Pull request by sidecontrol**

### CODE REVIEW

**Comment by justin-stephenson** [comment]
Hi Dan, can you remove the other 2 commits from this PR? Otherwise Ack from me.

**Comment by sidecontrol** [comment]
@justin-stephenson , mark it approved and I'll rebase it as the others get merged?

**Review by justin-stephenson — DISMISSED** [review]

**Review by ikerexxe — COMMENTED** [review]
LGTM but I won't approve until the other two PRs are merged. I'll review them again to check what's missing to merge them.

**Comment by sidecontrol** [comment]
@justin-stephenson, Now that I'm no longer testing the test code, I remove all irrelevant PRs. This is good to go now.

**Review by justin-stephenson — APPROVED** [review]
Ack. Thank you.

**Review by ikerexxe — APPROVED** [review]
LGTM. Thanks for the patch!

**Pull request merged**
